{% set name = 'sdv' %}
{% set version = '0.6.2.dev3' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - pytest-runner
    - graphviz
    - ctgan >=0.3.0,<0.4
    - exrex >=0.9.4,<0.11
    - numpy >=1.17.4,<2
    - pandas >=1.1,<1.1.5
    - python-graphviz >=0.13.2,<2.42.4
    - copulas >=0.3.3,<0.4
    - rdt >=0.2.10,<0.3
    - sdmetrics >=0.1.0,<0.2
    - deepecho ==0.1.3
  run:
    - python
    - graphviz
    - ctgan >=0.3.0,<0.4
    - exrex >=0.9.4,<0.11
    - numpy >=1.17.4,<2
    - pandas >=1.1,<1.1.5
    - python-graphviz >=0.13.2,<2.42.4
    - copulas >=0.3.3,<0.4
    - rdt >=0.2.10,<0.3
    - sdmetrics >=0.1.0,<0.2
    - deepecho ==0.1.3

about:
  home: "https://sdv.dev"
  license: MIT
  license_family: MIT
  license_file: "https://github.com/sdv-dev/SDV/blob/master/LICENSE"
  summary: "Synthetic Data Generation for tabular, relational and time series data."
  doc_url: "https://sdv.dev/SDV"
  dev_url: "https://github.com/sdv-dev/SDV"

extra:
  recipe-maintainers:
    - sdv-dev
