#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SDV documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.

import sdv

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.

extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.githubpages',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'IPython.sphinxext.ipython_console_highlighting',
    'sphinx_toolbox.collapse',
    'sphinx_reredirects'
]

ipython_execlines = [
    "from utils import is_valid, transform, reverse_transform",
    "import pandas as pd",
    "pd.set_option('display.width', 1000000)",
    "pd.set_option('display.max_columns', 1000)",
]

redirects = {
    './index.html': 'https://docs.sdv.dev/sdv',
    './user_guides/relational/hma1.html': 'https://docs.sdv.dev/sdv',
    './user_guides/relational/index.html': 'https://docs.sdv.dev/sdv',
    './user_guides/relational/constraints.html': 'https://docs.sdv.dev/sdv',
    './user_guides/relational/relational_metadata.html': 'https://docs.sdv.dev/sdv',
    './user_guides/relational/models.html': 'https://docs.sdv.dev/sdv',
    './user_guides/relational/data_description.html': 'https://docs.sdv.dev/sdv',
    './user_guides/index.html': 'https://docs.sdv.dev/sdv',
    './user_guides/timeseries/index.html': 'https://docs.sdv.dev/sdv',
    './user_guides/timeseries/par.html': 'https://docs.sdv.dev/sdv',
    './user_guides/timeseries/models.html': 'https://docs.sdv.dev/sdv',
    './user_guides/evaluation/index.html': 'https://docs.sdv.dev/sdv',
    './user_guides/evaluation/evaluation_framework.html': 'https://docs.sdv.dev/sdv',
    './user_guides/evaluation/synthetic_data_metrics.html': 'https://docs.sdv.dev/sdv',
    './user_guides/benchmarking/install.html': 'https://docs.sdv.dev/sdv',
    './user_guides/benchmarking/run.html': 'https://docs.sdv.dev/sdv',
    './user_guides/benchmarking/index.html': 'https://docs.sdv.dev/sdv',
    './user_guides/benchmarking/docker.html': 'https://docs.sdv.dev/sdv',
    './user_guides/benchmarking/datasets.html': 'https://docs.sdv.dev/sdv',
    './user_guides/benchmarking/synthesizers.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/copulagan.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/tabular_preset.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/index.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/constraints.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/handling_constraints.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/custom_constraints.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/tvae.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/table_metadata.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/models.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/ctgan.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/gaussian_copula.html': 'https://docs.sdv.dev/sdv',
    './user_guides/single_table/data_description.html': 'https://docs.sdv.dev/sdv',
    './_modules/index.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/timeseries/detection.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/timeseries/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/timeseries/efficacy/classification.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/timeseries/efficacy/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/demos.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/column_pairs/statistical/kl_divergence.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/goal.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/multi_table/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/multi_table/multi_single_table.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/multi_table/detection/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/multi_table/detection/parent_child.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/multi_column_pairs.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/privacy/cap.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/privacy/ensemble.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/privacy/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/privacy/numerical_sklearn.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/privacy/categorical_sklearn.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/privacy/radius_nearest_neighbor.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/efficacy/binary.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/efficacy/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/efficacy/multiclass.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/efficacy/regression.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/bayesian_network.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/detection/sklearn.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/detection/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/gaussian_mixture.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdmetrics/single_table/multi_single_column.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/evaluation.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/relational/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/relational/hma.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/timeseries/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/timeseries/deepecho.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/constraints/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/constraints/tabular.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/lite/tabular.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/tabular/copulagan.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/tabular/base.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/tabular/copulas.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/tabular/ctgan.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/sampling/tabular.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/sdv.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/demo.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/metadata/dataset.html': 'https://docs.sdv.dev/sdv',
    './_modules/sdv/metadata/table.html': 'https://docs.sdv.dev/sdv',
    './_static/webpack-macros.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/index.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/demos.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/relational.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/timeseries.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BNLikelihood.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.CSTest.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalEnsemble.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.SVCParentChildDetection.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.CSTest.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.DetectionMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryAdaBoostClassifier.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalMLP.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryMLPClassifier.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.BNLogLikelihood.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MulticlassMLPClassifier.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalSVM.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalPrivacyMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalRF.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.MultiTableMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalCAP.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalZeroCAP.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.DetectionMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalKNN.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.GMLogLikelihood.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryEfficacyMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.BNLikelihood.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalPrivacyMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.LogisticDetection.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.BNLogLikelihood.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MultiColumnPairsMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.SVCDetection.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalLR.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.KSComplement.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalSVR.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.LSTMClassifierEfficacy.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.LSTMDetection.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.SVCDetection.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CSTest.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.DiscreteKLDivergence.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.KSComplement.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.BNLikelihood.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MLPRegressor.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.LogisticParentChildDetection.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalRF.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.LogisticDetection.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalSVM.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BNLogLikelihood.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalSVM.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryAdaBoostClassifier.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.TimeSeriesDetectionMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalGeneralizedCAP.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.MultiSingleTableMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MultiSingleColumnMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalGeneralizedCAP.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BNLogLikelihood.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.SVCParentChildDetection.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.ContinuousKLDivergence.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.SVCDetection.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryLogisticRegression.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.SVCDetection.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalRF.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.LogisticDetection.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.LSTMClassifierEfficacy.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.LogisticDetection.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalSVR.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.DiscreteKLDivergence.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.LinearRegression.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.TimeSeriesDetectionMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.DiscreteKLDivergence.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalKNN.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalCAP.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.BNLikelihood.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CSTest.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MLEfficacyMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalMLP.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalEnsemble.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.demos.load_multi_table_demo.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.KSComplement.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.KSComplement.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalRadiusNearestNeighbor.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalNB.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.SVCDetection.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MultiColumnPairsMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.demos.load_timeseries_demo.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MulticlassMLPClassifier.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MulticlassDecisionTreeClassifier.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CSTest.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.KSComplement.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.ContinuousKLDivergence.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MulticlassMLPClassifier.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalLR.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.LSTMDetection.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.MultiTableMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.LinearRegression.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BNLikelihood.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.DetectionMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalZeroCAP.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryDecisionTreeClassifier.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryLogisticRegression.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.TimeSeriesEfficacyMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.LogisticDetection.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.GMLogLikelihood.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalNB.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.demos.load_single_table_demo.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.SingleTableMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryAdaBoostClassifier.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryDecisionTreeClassifier.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryMLPClassifier.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalKNN.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalMLP.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.MultiSingleTableMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.LogisticParentChildDetection.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.CSTest.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalPrivacyMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalLR.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MLPRegressor.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MLPRegressor.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryEfficacyMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalSVR.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalEnsemble.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalGeneralizedCAP.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.ScikitLearnClassifierDetectionMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.LSTMDetection.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.LinearRegression.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MulticlassDecisionTreeClassifier.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.LogisticDetection.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryLogisticRegression.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.TimeSeriesMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BNLogLikelihood.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.DetectionMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.ParentChildDetectionMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalNB.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.SVCDetection.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.ContinuousKLDivergence.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryDecisionTreeClassifier.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalCAP.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.TimeSeriesEfficacyMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.SingleTableMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.LSTMClassifierEfficacy.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BinaryMLPClassifier.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.ScikitLearnClassifierDetectionMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalPrivacyMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.ParentChildDetectionMetric.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MulticlassEfficacyMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.RegressionEfficacyMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.KSComplement.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.timeseries.TimeSeriesMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.CategoricalZeroCAP.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.BNLikelihood.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.LogisticParentChildDetection.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalRadiusNearestNeighbor.compute.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.NumericalRadiusNearestNeighbor.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.SVCParentChildDetection.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.GMLogLikelihood.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.relational.BNLogLikelihood.get_subclasses.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MultiSingleColumnMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MulticlassDecisionTreeClassifier.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/api/sdv.metrics.tabular.MLEfficacyMetric.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metrics/tabular.html': 'https://docs.sdv.dev/sdv',
    './api_reference/evaluation.html': 'https://docs.sdv.dev/sdv',
    './api_reference/relational/hma1.html': 'https://docs.sdv.dev/sdv',
    './api_reference/relational/index.html': 'https://docs.sdv.dev/sdv',
    './api_reference/relational/api/sdv.relational.hma.HMA1.load.html': 'https://docs.sdv.dev/sdv',
    './api_reference/relational/api/sdv.relational.hma.HMA1.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/relational/api/sdv.relational.hma.HMA1.save.html': 'https://docs.sdv.dev/sdv',
    './api_reference/relational/api/sdv.relational.hma.HMA1.html': 'https://docs.sdv.dev/sdv',
    './api_reference/relational/api/sdv.relational.hma.HMA1.sample.html': 'https://docs.sdv.dev/sdv',
    './api_reference/index.html': 'https://docs.sdv.dev/sdv',
    './api_reference/timeseries/index.html': 'https://docs.sdv.dev/sdv',
    './api_reference/timeseries/par.html': 'https://docs.sdv.dev/sdv',
    './api_reference/timeseries/api/sdv.timeseries.deepecho.PAR.load.html': 'https://docs.sdv.dev/sdv',
    './api_reference/timeseries/api/sdv.timeseries.deepecho.PAR.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/timeseries/api/sdv.timeseries.deepecho.PAR.save.html': 'https://docs.sdv.dev/sdv',
    './api_reference/timeseries/api/sdv.timeseries.deepecho.PAR.sample.html': 'https://docs.sdv.dev/sdv',
    './api_reference/timeseries/api/sdv.timeseries.deepecho.PAR.html': 'https://docs.sdv.dev/sdv',
    './api_reference/timeseries/api/sdv.timeseries.deepecho.PAR.get_metadata.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/index.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/base.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Range.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarRange.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Unique.fit_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Constraint.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Positive.is_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.FixedCombinations.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Unique.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Unique.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.OneHotEncoding.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarInequality.fit_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Inequality.fit_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Inequality.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Range.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.OneHotEncoding.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Range.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Unique.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Positive.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Constraint.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Constraint.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Negative.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarInequality.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarInequality.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.FixedCombinations.is_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Positive.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Range.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.FixedCombinations.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Inequality.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Negative.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.OneHotEncoding.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Positive.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Negative.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Range.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarRange.is_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Inequality.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarInequality.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarInequality.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Negative.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarRange.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarRange.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Constraint.is_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarInequality.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarInequality.is_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.FixedCombinations.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Positive.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Constraint.fit_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.FixedCombinations.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Negative.is_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Negative.fit_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarRange.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Negative.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Constraint.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarRange.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Constraint.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Inequality.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Unique.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.FixedCombinations.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Negative.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Inequality.is_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Unique.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Constraint.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.OneHotEncoding.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.OneHotEncoding.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Positive.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Constraint.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.FixedCombinations.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.OneHotEncoding.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Unique.is_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Inequality.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Range.fit_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.OneHotEncoding.fit_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Negative.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Unique.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Positive.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarRange.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.OneHotEncoding.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Inequality.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Range.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.FixedCombinations.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarRange.fit_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.OneHotEncoding.is_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Inequality.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarInequality.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.FixedCombinations.fit_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Range.is_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarInequality.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.ScalarRange.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Positive.fit_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Range.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Unique.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/api/sdv.constraints.Positive.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/constraints/tabular.html': 'https://docs.sdv.dev/sdv',
    './api_reference/lite/index.html': 'https://docs.sdv.dev/sdv',
    './api_reference/lite/api/sdv.lite.tabular.TabularPreset.sample_remaining_columns.html': 'https://docs.sdv.dev/sdv',
    './api_reference/lite/api/sdv.lite.tabular.TabularPreset.sample.html': 'https://docs.sdv.dev/sdv',
    './api_reference/lite/api/sdv.lite.tabular.TabularPreset.load.html': 'https://docs.sdv.dev/sdv',
    './api_reference/lite/api/sdv.lite.tabular.TabularPreset.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/lite/api/sdv.lite.tabular.TabularPreset.html': 'https://docs.sdv.dev/sdv',
    './api_reference/lite/api/sdv.lite.tabular.TabularPreset.sample_conditions.html': 'https://docs.sdv.dev/sdv',
    './api_reference/lite/api/sdv.lite.tabular.TabularPreset.save.html': 'https://docs.sdv.dev/sdv',
    './api_reference/lite/api/sdv.lite.tabular.TabularPreset.list_available_presets.html': 'https://docs.sdv.dev/sdv',
    './api_reference/lite/tabular.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/copulagan.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/index.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/tvae.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.CTGAN.load.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.CTGAN.sample_conditions.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulagan.CopulaGAN.load.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulagan.CopulaGAN.sample_conditions.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.TVAE.sample_conditions.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.TVAE.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulagan.CopulaGAN.get_metadata.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.CTGAN.sample.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.CTGAN.get_metadata.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.sample.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulagan.CopulaGAN.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.TVAE.save.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.load.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.set_parameters.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.get_likelihood.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.sample_remaining_columns.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulagan.CopulaGAN.sample.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.CTGAN.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.get_distributions.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.TVAE.sample.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.TVAE.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.CTGAN.sample_remaining_columns.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.get_metadata.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulagan.CopulaGAN.get_distributions.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulagan.CopulaGAN.save.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.CTGAN.save.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.TVAE.get_metadata.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulagan.CopulaGAN.sample_remaining_columns.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.TVAE.sample_remaining_columns.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.get_parameters.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.sample_conditions.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulagan.CopulaGAN.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.CTGAN.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.copulas.GaussianCopula.save.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/api/sdv.tabular.ctgan.TVAE.load.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/copulas.html': 'https://docs.sdv.dev/sdv',
    './api_reference/tabular/ctgan.html': 'https://docs.sdv.dev/sdv',
    './api_reference/sampling/index.html': 'https://docs.sdv.dev/sdv',
    './api_reference/sampling/api/sdv.sampling.Condition.html': 'https://docs.sdv.dev/sdv',
    './api_reference/sampling/api/sdv.sampling.Condition.get_column_values.html': 'https://docs.sdv.dev/sdv',
    './api_reference/sampling/api/sdv.sampling.Condition.get_num_rows.html': 'https://docs.sdv.dev/sdv',
    './api_reference/sampling/tabular.html': 'https://docs.sdv.dev/sdv',
    './api_reference/sdv.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.SDV.save.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.demo.load_tabular_demo.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.SDV.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.evaluation.evaluate.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.demo.load_timeseries_demo.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.demo.get_available_demos.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.SDV.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.demo.load_demo.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.SDV.sample_all.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.SDV.load.html': 'https://docs.sdv.dev/sdv',
    './api_reference/api/sdv.SDV.sample.html': 'https://docs.sdv.dev/sdv',
    './api_reference/demo.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/dataset.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/index.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/table.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.get_foreign_keys.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.from_json.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.filter_valid.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.visualize.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.validate.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.to_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.fit.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.add_field.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.reverse_transform.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.load_tables.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.load_table.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.get_dtypes.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.from_dict.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.get_tables.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.get_fields.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.set_model_kwargs.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.get_fields.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.get_parents.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.get_primary_key.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.get_table_meta.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.add_relationship.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.get_field_meta.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.add_table.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.set_primary_key.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.get_model_kwargs.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.get_dtypes.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.set_primary_key.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.table.Table.to_json.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.get_children.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.to_json.html': 'https://docs.sdv.dev/sdv',
    './api_reference/metadata/api/sdv.metadata.dataset.Metadata.html': 'https://docs.sdv.dev/sdv',
    './history.html': 'https://docs.sdv.dev/sdv',
    './genindex.html': 'https://docs.sdv.dev/sdv',
    './developer_guides/index.html': 'https://docs.sdv.dev/sdv',
    './developer_guides/overview.html': 'https://docs.sdv.dev/sdv',
    './developer_guides/contributing.html': 'https://docs.sdv.dev/sdv',
    './developer_guides/sdv/index.html': 'https://docs.sdv.dev/sdv',
    './developer_guides/sdv/constraints.html': 'https://docs.sdv.dev/sdv',
    './developer_guides/sdv/metadata.html': 'https://docs.sdv.dev/sdv',
    './developer_guides/sdv/tabular.html': 'https://docs.sdv.dev/sdv',
    './search.html': 'https://docs.sdv.dev/sdv',
    './getting_started/quickstart.html': 'https://docs.sdv.dev/sdv',
    './getting_started/install.html': 'https://docs.sdv.dev/sdv',
    './getting_started/index.html': 'https://docs.sdv.dev/sdv'
 }

# Add any paths that contain templates here, relative to this directory.
templates_path = ['sdv_theme/_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'SDV'
slug = 'sdv'
title = project + ' Documentation',
copyright = '2022, DataCebo, Inc.'
author = 'DataCebo, Inc.'
description = 'Synthetic Data Generation for tabular, relational and time series data.'
user = 'sdv-dev'

# New docs for V1.0 Beta announcement
rst_prolog = """
    .. admonition:: Try the new SDV 1.0 Beta!

        We are transitioning to a new version of SDV with improved workflows, new features
        and an updated documentation site.

        `Click here to go to the new docs pages. <https://docs.sdv.dev/sdv/>`_
"""

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = sdv.__version__
# The full version, including alpha/beta/rc tags.
release = sdv.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['.py', '_build', 'Thumbs.db', '.DS_Store', '**.ipynb_checkpoints']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sdv_theme'
html_theme_path = ['.']

# Readthedocs additions
html_context = {
    'display_github': True,
    'github_user': user,
    'github_repo': project,
    'github_version': 'main',
    'conf_py_path': '/docs/',
}

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {
#     'collapse_navigation': True,
#     'display_version': True,
# }
html_theme_options = {
    "github_url": "https://github.com/sdv-dev/SDV",
    "twitter_url": "https://twitter.com/sdv_dev",
    "slack_url": "https://bit.ly/sdv-slack-invite",
    "show_prev_next": True,
    "google_analytics_id": "UA-180602145-3",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = [
    'sdv_theme/static',
    'images',
]
html_css_files = [
    'sdv.css',
]

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = 'images/SDV.ico'

# If given, this must be the name of an image file (path relative to the
# configuration directory) that is the logo of the docs. It is placed at
# the top of the sidebar; its width should therefore not exceed 200 pixels.
html_logo = 'images/SDV.png'

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = slug + 'doc'


# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
latex_documents = [(
    master_doc,
    slug + '.tex',
    title,
    author,
    'manual'
)]


# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(
    master_doc,
    slug,
    title,
    [author],
    1
)]


# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [(
    master_doc,
    slug,
    title,
    author,
    slug,
    description,
    'Miscellaneous'
)]
