name: Check Milestone

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  preparerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up latest Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install requests==2.31.0
            python -m pip install .[dev]

      - name: Check for prerelease dependencies
        run: python scripts/check_for_prereleases.py

      - name: Check milestone
        env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: >
            python -m scripts.check_milestone -p ${{ github.event.number }}
