# name: Check Milestone

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: The PR number
        required: true

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  preparerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up latest Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install requests==2.31.0
            python -m pip install .[dev]

      - name: Get PR number
        run: |
            echo "PR_NUMBER=${{ inputs.pr_number ||  github.event.number }}" >> $GITHUB_ENV

      - name: Check milestone
        env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: >
            python -m scripts.check_milestone -p ${{ env.PR_NUMBER }}
