name: Deprecated Python CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 3' # Every Wednesday at 20:00 UTC
  push:
    branches:
      - issue-2681-py38

jobs:
  tests:
    name: Test on Python ${{ matrix.python-version }} (deprecated)
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.7'
            os: ubuntu-22.04
          - python-version: '3.8'
            os: ubuntu-latest
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install specified dependencies (unpinned)
        run: |
            # Install the provided dependency set without version pins
            python -m pip install \
            Faker MarkupSafe anyio argon2-cffi argon2-cffi-bindings arrow asttokens async-lru attrs \
            babel beautifulsoup4 bleach boto3 botocore cachetools certifi cffi charset_normalizer \
            cloudpickle comm copulas coverage ctgan debugpy decorator deepecho defusedxml et-xmlfile \
            executing fastjsonschema filelock fqdn fsspec gitdb gitpython google-api-core \
            google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib \
            googleapis-common-protos graphviz h11 httpcore httplib2 httpx idna iniconfig invoke \
            ipykernel ipython ipywidgets isoduration jedi jinja2 jmespath \
            joblib json5 jsonpointer jsonschema jsonschema-specifications jupyter jupyter-client \
            jupyter-console jupyter-core jupyter-events jupyter-lsp jupyter-server \
            jupyter-server-terminals jupyterlab jupyterlab-pygments jupyterlab-server \
            jupyterlab_widgets lark matplotlib-inline mistune mpmath nbclient nbconvert \
            nbformat nest-asyncio networkx notebook notebook-shim numpy \
            nvidia-cublas-cu12 nvidia-cuda-cupti-cu12 nvidia-cuda-nvrtc-cu12 nvidia-cuda-runtime-cu12 \
            nvidia-cudnn-cu12 nvidia-cufft-cu12 nvidia-cufile-cu12 nvidia-curand-cu12 \
            nvidia-cusolver-cu12 nvidia-cusparse-cu12 nvidia-cusparselt-cu12 nvidia-nccl-cu12 \
            nvidia-nvjitlink-cu12 nvidia-nvshmem-cu12 nvidia-nvtx-cu12 \
            oauthlib odfpy openpyxl packaging pandas pandocfilters parso pexpect platformdirs plotly \
            pluggy prometheus-client prompt_toolkit proto-plus protobuf psutil ptyprocess pure-eval \
            pyarrow pyasn1 pyasn1-modules pycparser pygments pyparsing pytest pytest-cov \
            pytest-rerunfailures pytest-runner python-calamine python-dateutil python-json-logger \
            pytz pyxlsb pyyaml pyzmq rdt referencing requests requests-oauthlib rfc3339-validator \
            rfc3986-validator rsa s3transfer scikit-learn scipy sdmetrics \
            send2trash setuptools six slack-sdk smmap sniffio soupsieve stack_data sympy terminado \
            threadpoolctl tinycss2 tomli torch tornado tqdm traitlets typing-extensions tzdata \
            uri-template uritemplate urllib3 wcwidth webcolors webencodings websocket-client \
            widgetsnbextension xlrd xlsxwriter

      - name: Run unit tests
        run: invoke unit
      - name: Run integration tests
        run: invoke integration
