name: Deprecated Python CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 3' # Every Wednesday at 20:00 UTC
  push:
    branches:
      - issue-2681-py38

jobs:
  tests:
    name: Test on Python ${{ matrix.python-version }} (deprecated)
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.8'
            os: ubuntu-latest
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Relax requires-python lower bound for installation
        run: |
          sed -i.bak -E "s/requires-python = '>=3\.[0-9]+/requires-python = '>=${{ matrix.python-version }}/" pyproject.toml
          grep -n "requires-python" pyproject.toml

      - name: Install package and test dependencies
        run: python -m pip install invoke .[test]

      - name: Run unit tests
        run: invoke unit
      - name: Run integration tests
        run: invoke integration
