name: Static Code Analysis

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install bandit==1.7.7
    - name: Save code analysis
      run: bandit -r . -x ./tests -f txt -o static_code_analysis.txt --exit-zero
    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        commit-message: Update static code analysis
        author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        title: Latest Code Analysis
        body: "This is an auto-generated PR with the **latest** code analysis results."
        branch: static-code-analysis
        branch-suffix: short-commit-hash
        base: main
